image: python:3.9

variables:
  USE_SYSTEM_PYTHON: 3
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - cache.tar.gz

before_script:
  - bash ci.sh extract-cache
  - bash ci.sh install-packages

stages:
  - test
  - deploy

test-all:
  stage: test
  script:
    - bash ci.sh test
    - bash ci.sh create-cache

deploy-pypi:
  stage: deploy
  only:
    - tags
  script:
    - bash ci.sh build
    - bash ci.sh deploy
    - bash ci.sh create-cache
