name: python-deploy

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  USE_SYSTEM_PYTHON: __PYTHON_MAJOR__

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: setup python __PYTHON_MAJOR__.__PYTHON_MINOR__
        uses: actions/setup-python@v1
        with:
          python-version: __PYTHON_MAJOR__.__PYTHON_MINOR__

      - name: pip caching
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.main.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.deploy.txt
          python -m pip install -r requirements.main.txt

      - name: Build package
        run: |
          python setup.py bdist_wheel

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
